#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");

const rootDir = __dirname;
const srcDir = path.join(rootDir, "src");
const presetsDir = path.join(rootDir, "presets");
const outFile = path.join(rootDir, "app.js");
const generatedPresetsFile = path.join(srcDir, "01b-game-presets.js");

function loadGamePresets() {
  const indexPath = path.join(presetsDir, "index.json");
  if (!fs.existsSync(indexPath)) {
    console.error("Missing presets/index.json");
    process.exit(1);
  }
  const index = JSON.parse(fs.readFileSync(indexPath, "utf8"));
  const ids = Array.isArray(index) ? index : index.presets;
  if (!Array.isArray(ids) || ids.length === 0) {
    console.error("presets/index.json must list preset ids in \"presets\"");
    process.exit(1);
  }
  return ids.map((id) => {
    const file = path.join(presetsDir, id + ".json");
    if (!fs.existsSync(file)) {
      console.error("Missing preset file:", file);
      process.exit(1);
    }
    const preset = JSON.parse(fs.readFileSync(file, "utf8"));
    if (!preset.id) preset.id = id;
    if (preset.id !== id) {
      console.error("Preset id mismatch:", file, "has id", preset.id, "but index lists", id);
      process.exit(1);
    }
    if (!preset.name) {
      console.error("Preset missing name:", file);
      process.exit(1);
    }
    return preset;
  });
}

function writeGeneratedPresets(presets) {
  const body = JSON.stringify(presets, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : "  " + line))
    .join("\n");
  const out =
    "  // GENERATED by build.js from presets/*.json — do not edit by hand.\n" +
    "  const GAME_PRESETS = " +
    body +
    ";\n";
  fs.writeFileSync(generatedPresetsFile, out);
}

const files = [
  "00-firebase.js",
  "01-core.js",
  "01b-game-presets.js",
  "02-modals.js",
  "03-games.js",
  "04-shared.js",
  "05-page-dailies.js",
  "06-page-weeklies.js",
  "07-page-endgame.js",
  "08-page-attendance.js",
  "08b-page-extracurricular.js",
  "09-page-data.js",
  "10-page-games.js",
  "11-page-home.js",
  "12-main.js",
  "mobile-integration.js",
];

const gamePresets = loadGamePresets();
writeGeneratedPresets(gamePresets);

const parts = files.map((f) => {
  const p = path.join(srcDir, f);
  if (!fs.existsSync(p)) {
    console.error("Missing file:", p);
    process.exit(1);
  }
  return fs.readFileSync(p, "utf8");
});

const header =
  "/**\n" +
  " * GENERATED — edit src/* and presets/*.json, then run: node build.js\n" +
  " */\n";

fs.writeFileSync(outFile, header + parts.join("\n"));
console.log("Built app.js from", files.length, "source files +", gamePresets.length, "game presets.");

